### ISSUE TITLE
do ssh keycan or disable strict host verification during checkout

### ISSUE THREAD

**Issue by bash-stack** [repman-io/repman#173] opened 2020-05-22 15:23 UTC
as suggested , git checkout from custom gitlab / git url was tried  , 

- [ ]  repman still uses /root/ directory , chown /chgrp was necessary to make it work 
- [ ]  synchronization Error :

```
Error: Failed to execute git clone --mirror 'git@mygitlab.istance/path/to/repo.git' '/root/.composer/cache/vcs/my-gitlab-group-path.git/'

Cloning into bare repository '/root/.composer/cache/vcs/my-gitlab-group-path.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by akondas** [comment] 2020-05-23 07:01
I will try to reproduce this problem locally, but it seems to me that it is a matter of configuring the instance. When using docker images I don't have such an error.

**Comment by akondas** [comment] 2020-06-24 05:53
Hey @bash-stack, can we reproduce this error (preferably on a public instance `app.repman.io`)? If not and we managed to solve it, can we close this issue then?

**Comment by akondas** [comment] 2020-10-22 09:30
This seems to be a problem with individual instance configuration. Due to the fact that I did not manage to recreate it, I close this thread for the moment.

In case of further problems, please feel free to reopen this issue or create a new one.

**Closed by akondas** 2020-10-22 09:30 UTC
Labels: question
