### ISSUE TITLE
Package synchronization stuck

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#73] opened 2020-04-21 20:27 UTC
Hi !

I've added a package from a repository where Repman do not have access, and the sync is stuck, and there is no way to delete the package.

![image](https://user-images.githubusercontent.com/794449/79910506-d9ee1200-83ec-11ea-829b-108a7c901219.png)

Have a good day,
Samuel

**Comment by akondas** [comment] 2020-04-21 20:45
Is the consumer runnig? You need to run 

```
bin/console messenger:consume async
```

**Comment by sadortun** [comment] 2020-04-21 21:33
Yes, it's running

**Comment by akondas** [comment] 2020-04-21 21:41
Ok then i have to reproduce it. Normally it is so that if an error occurred during synchronization it is displayed on the package list.

**Comment by akondas** [comment] 2020-04-21 22:40
Normally in such a situation something like what I shared on this screen follows:
![Screenshot from 2020-04-22 00-38-12](https://user-images.githubusercontent.com/8239917/79921013-aa152d80-8431-11ea-86c6-910e6ea1d9b0.png)
Are you able to share application logs? Or did it happen on our public instance?

**Comment by sadortun** [comment] 2020-04-21 22:50
@akondas Yes, i saw this message on later packages due tu access issues.  

During the first addition of the package it might be possible that the message consumer was not running. 

Sorry, i dont have any logs.

**Comment by sadortun** [comment] 2020-04-22 04:54
Ill close this since it's probably only an issue with my incorect initial setup.

**Comment by akondas** [comment] 2020-04-22 05:13
> consumer was not running

This should not be a problem, when you start the consumer, all the work that was in the queue resumes.

You can try to run:
```php
bin/console messenger:failed:show
```

**Comment by akondas** [comment] 2020-04-27 14:53
@sadortun have you tried `bin/console messenger:failed:show`? If yes, and still no errors then can we close this? (because at the moment it's difficult to reproduce)

**Comment by sadortun** [comment] 2020-04-27 17:08
No i did not. I think we can close this anyway, until we get a better way to reproduce the issue

**Comment by sadortun** [comment] 2020-05-09 02:58
Same issue occured again 
![image](https://user-images.githubusercontent.com/794449/81462282-764f3d00-917f-11ea-83b0-a8f7d09a118b.png)

**Comment by akondas** [comment] 2020-05-11 05:27
The next step is the nginx and/or php-fpm logs:
- `/var/log/nginx/app_error.log`
- `/var/log/php7.4-fpm.log`

**Comment by akondas** [comment] 2020-05-20 06:05
Hey @sadortun, can we also check:
- [ ] message consumer logs `var/log/consumer.log`
- [ ] supervisor logs `/var/log/supervisor/message-consumer_00-stderr ...`

I  would like to solve this problem :wink:

**Comment by akondas** [comment] 2020-10-22 09:20
Thanks @sadortun for your time with. I think we can close it for now. All helpful information on where to look for errors will be included in the new documentation tab: https://github.com/repman-io/repman-docs-pages/issues/13

In case of further news, please feel free to open this issue or create a new one.

**Closed by akondas** 2020-10-22 09:20 UTC
Labels: bug
