### ISSUE TITLE
GitLab package list limited to 40

### ISSUE THREAD

**Issue by iainfogg** [repman-io/repman#85] opened 2020-04-22 14:09 UTC
I've got access to a lot more than 40 repos in GitLab, but only 40 appear in the packages list when trying to add a new package. I assume this is because of an issue with the pagination in the GitLab API, but because there's no way to manually add a repo, I'm unable to add any repos that don't appear in those 40.

**Comment by akondas** [comment] 2020-04-22 18:28
Currently the paging mechanism is added and should download all repositories. But maybe we fetch them in a bad way. We are using `m4tthumphrey/php-gitlab-api` with this options:
```
$this->pager->fetchAll($this->client->projects(), 'all', [[
            'simple' => true,
            'owned' => true,
            'membership' => true,
            'order_by' => 'path',
        ]]))
```
flag desc:
```
@var bool   $owned       Limit by projects owned by the current user.
@var bool   $membership  Limit by projects that the current user is a member of.
```



Maybe some specific type of project is missing?

**Comment by akondas** [comment] 2020-04-24 09:36
Hello @iainfogg I checked the api and everything looks correct, we fetch a list of all projects, even if they do not fit on one page (which is not the best either).

Have you tried entering the name of the repository you were looking for? Maybe just not everything is displayed in this html component (or there may be a problem with js).

**Comment by iainfogg** [comment] 2020-04-24 10:23
Hi, yeah I've tried entering the full name of a package that's not in the 40, but it doesn't appear. if I examine the HTML in the page, the one I entered isn't in there either.

In the dropdown, I can't make any particular sense of the order - it's not in package, group or date order, so that doesn't help with any diagnostics I'm afraid.

**Comment by akondas** [comment] 2020-04-24 10:29
Thanks for the information. It seems to me that I am able to reproduce this situation. The problem is probably with workspace projects in which the user is not the owner.

**Comment by akondas** [comment] 2020-04-27 14:54
Hey, @iainfogg can you check please again and possibly close the issue if the problem is resolved?

**Comment by iainfogg** [comment] 2020-04-27 16:10
Hi @akondas - it's better now, but still not fully there. I have maybe 90 repos in GitLab, organised into subgroups. Originally when I raised the issue, only 3 of the approximately 60 repos in a subgroup (where all my packages are) were appearing. Now, if I type the name of the subgroup it shows 10 rather than 3.

Also, if I just type the name of a package which is in that group, but is not appearing in the list of 10, it does not appear either.

**Comment by akondas** [comment] 2020-04-27 18:10
Hi @iainfogg, Are you the owner of all repositories? Because I tested this variant with a group that had over 70 projects and everything worked. Maybe they could be found manually? The purpose of my questions is to separate the filter in JS from repo downloading via API.

I am asking you to develop what you mean in `subgroups`?

**Comment by iainfogg** [comment] 2020-04-28 07:37
Hi @akondas - I am an owner in the top level group, and therefore all subgroups. Below the top level group, we have a number of subgroups, and almost all our repos sit in one of those subgroups rather than sitting directly under the top level group. So, for example, we have a subgroup for our composer packages, and another for our web applications, and another for stuff we are messing around with.

Also, there are a small number of situations where one of the subgroups has it's own subgroup, but the repos I'm looking for are not in this scenario - I just mention it in case there's any recursion issues which may be causing the problem, although I doubt that.

Is there anything else that would help you?

Thanks for digging into this.

**Comment by akondas** [comment] 2020-04-28 16:47
Wiat, I wasn't aware that there is a subgroup option on GitLab (https://docs.gitlab.com/ee/user/group/subgroups/), I haven't tested it yet, but it means we should be able to fix it :wink:

**Comment by karniv00l** [comment] 2020-04-28 17:04
Hi @iainfogg, will you be willing try to unlink your Gitlab account and try again? Maybe this helps. You can unlink gitlab in your user profile, we've added this feature in `0.1.2`.

**Comment by iainfogg** [comment] 2020-04-29 11:35
Hi @karniv00l - I've unlinked and relinked, but I'm afraid I'm still only getting a small number of repos from my composer pacakges subgroup.

**Comment by akondas** [comment] 2020-05-04 18:01
Hey @iainfogg, after a long search, we finally managed to reproduce the problem. Long story short: missing `curl` extension in prod env (you can read more here: https://github.com/m4tthumphrey/php-gitlab-api/issues/319#issuecomment-623611855).

At this time, everything should work properly, if there is still a problem, please re-open this issue confidently.

Thank you very much for your cooperation and patience :clap: :medal_sports:

**Closed by akondas** 2020-05-04 18:01 UTC
Labels: bug
