### ISSUE TITLE
repman-io/composer-plugin causes The checksum verification of the file failed

### ISSUE THREAD

**Issue by ProxiBlue** [repman-io/repman#153] opened 2020-05-12 02:40 UTC
Hello,

So here is the situation:

I am running a composer.json with the following repositories setup.
Take note that repo.repman.io is not directly part of my wanted list of repos.
That is intentional. There is a custom private repo.

```
"repositories": {
        "0": {
            "type": "path",
            "url": "./vendor-repo/*/*",
            "options": {
                "symlink": true
            }
        },
        "1": {
            "type": "composer",
            "url": "http://satis.example.com:8181"
        },
        "2": {
            "type": "composer",
            "url": "https://private.repo.repman.io"
        },
        "packagist.org": false,
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool"
        }
    },
```
Your package manager plugin is installed at this point.
This is running in a clean folder. This is the first time composer is run, and there is no lock file.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 507 installs, 0 updates, 0 removals
  - Installing magento/zendframework1 (1.14.3): Downloading (100%)         
 Failed, trying the next URL (0: The checksum verification of the file failed (downloaded from https://repo.repman.io/dists/magento/zendframework1/1.14.3.0/726855dfb080089dc7bc7b016624129f8e7bc4e5.zip))Downloading (100%)         
  - Installing laminas/laminas-zendframework-bridge (1.0.3): Downloading (100%)         
 Failed, trying the next URL (0: The checksum verification of the file failed (downloaded from https://repo.repman.io/dists/laminas/laminas-zendframework-bridge/1.0.3.0/bfbbdb6c998d50dbf69d2187cb78a5f1fa36e1e9.zip))Downloading (100%)         
  - Installing laminas/laminas-stdlib (3.2.1): Downloading (100%)         
 Failed, trying the next URL (0: The checksum verification of the file failed (downloaded from https://repo.repman.io/dists/laminas/laminas-stdlib/3.2.1.0/2b18347625a2f06a1a485acfbc870f699dbe51c6.zip))Downloading (100%)         
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)         
 Failed, trying the next URL (0: The checksum verification of the file failed (downloaded from https://repo.repman.io/dists/container-interop/container-interop/1.2.0.0/79cbf1341c22ec75643d841642dd5d6acd83bdb8.zip))Downloading (100%)         
  - Installing laminas/laminas-validator (2.13.4): Downloading (connecting...)^C
```
and continues as above example

I took note that these are pointing to repo.repman.io
I removed your composer plugin:

```
02:21 $ composer global remove repman-io/composer-plugin
Changed current directory to /home/vagrant/.composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing repman-io/composer-plugin (0.1.3)
Writing lock file
Generating autoload files
```

after which the same composer install/update commands work.

The satis.example.com:8181 repo is 100% satis composer repo, which is a mirror for packages we use in the site (magento2)

**Comment by akondas** [comment] 2020-05-12 04:30
Hello @ProxiBlue, as you can see `Failed, trying the next URL` does not mean `completely breaks`. Repman composer plugin works as packagist proxy, and in case of failure, composer will skip its result using the source link.

The real problem is ` The checksum verification of the file failed` which is a known problem and as soon as I can come up with a solution, it will be fixed. I am working on a patch to support older configurations (tar files in #139). Until then, you could paste a fragment of the composer.lock file here so that I can reproduce the problem better.

**Comment by ProxiBlue** [comment] 2020-05-12 05:02
I will have to recreate the issue, knee deep in the middle of work, will try and get that to in a timely manner.

**Comment by akondas** [comment] 2020-07-17 07:06
@ProxiBlue is this problem still occurring? Can you help me recreate it?

**Comment by akondas** [comment] 2020-10-22 09:25
Due to the inability to reproduce this problem, I am closing it for now. Please go ahead and reopen in case of further problems (or create a new issue).

**Closed by akondas** 2020-10-22 09:25 UTC
Labels: bug
